yolo_model:

  config_file:
    name: plant-weed-yolov3-tiny-r0.cfg
  weight_file:
    name: plant-weed-yolov3-tiny-r0_best.weights
  threshold:
    value: 0.4
  detection_classes:
    names:
      - weed
      - plant

