yolo_model:

  config_file:
    name: plant-weed-yolov3-tiny-r0.cfg
  weight_file:
    name: plant-weed-yolov3-tiny-r0_best.weights
  threshold:
<<<<<<< Updated upstream
    value: 0.25
  detection_sclasses:
=======
    value: 0.2
  detection_classes:
>>>>>>> Stashed changes
    names:
      - weed
      - plant

