yolo_model:

  config_file:
    name: plant-weed-yolov3-tiny-r0.cfg
  weight_file:plant-weed-yolov3-tiny-r0_best.weights
    name: 
  threshold:
    value: 0.25
  detection_sclasses:
    names:
      - weed
      - plant

