yolo_model:

  config_file:
    name: plant-weed-yolov3-tiny.cfg
  weight_file:
    name: plant-weed-yolov3-tiny_final.weights
  threshold:
    value: 0.4
  detection_classes:
    names:
      - weed
      - plant

